export var Schools = [
    {
        "name": "Bridgeland",
        "shortname": "bridgeland",
        "website": "http://bridgeland.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_016.html",
        "bells": "http://bridgeland.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://bridgeland.cfisd.net/en/news/school-news/",
        "studentnews": "http://bhsthebridge.com/",
        "colorA": "bridgeland-colorA",
        "colorB": "bridgeland-colorB",
        "colorC": "bridgeland-colorC",
        "schooltype": "high"
    },
    {
        "name": "Cy-Fair",
        "shortname": "cyfair",
        "website": "http://cyfair.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_002.html",
        "bells": "http://cyfair.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://cyfair.cfisd.net/en/news/school-news/",
        "studentnews": null,
        "colorA": "cyfair-colorA",
        "colorB": "cyfair-colorB",
        "colorC": "cyfair-colorC",
        "schooltype": "high"
    },
    {
        "name": "Cypress Creek",
        "shortname": "cypresscreek",
        "website": "http://cycreek.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_004.html",
        "bells": "http://cycreek.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://cycreek.cfisd.net/en/news/school-news/",
        "studentnews": "https://www.cchspress.com/",
        "colorA": "cypresscreek-colorA",
        "colorB": "cypresscreek-colorB",
        "colorC": "cypresscreek-colorC",
        "schooltype": "high"
    },
    {
        "name": "Cypress Falls",
        "shortname": "cypressfalls",
        "website": "http://cyfalls.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_007.html",
        "bells": "http://cyfalls.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://cyfalls.cfisd.net/en/news/school-news/",
        "studentnews": "https://www.cfwingspan.com/",
        "colorA": "cypressfalls-colorA",
        "colorB": "cypressfalls-colorB",
        "colorC": "cypressfalls-colorC",
        "schooltype": "high"
    },
    {
        "name": "Cypress Lakes",
        "shortname": "cypresslakes",
        "website": "http://cylakes.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_013.html",
        "bells": "http://cylakes.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://cylakes.cfisd.net/en/news/school-news/",
        "studentnews": "http://thelakeview.co/",
        "colorA": "cypresslakes-colorA",
        "colorB": "cypresslakes-colorB",
        "colorC": "cypresslakes-colorC",
        "schooltype": "high"
    },
    {
        "name": "Cypress Park",
        "shortname": "cypresspark",
        "website": "http://cypark.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_015.html",
        "bells": "http://cypark.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://cypark.cfisd.net/en/news/school-news/",
        "studentnews": null,
        "colorA": "cypresspark-colorA",
        "colorB": "cypresspark-colorB",
        "colorC": "cypresspark-colorC",
        "schooltype": "high"
    },
    {
        "name": "Cypress Ranch",
        "shortname": "cypressranch",
        "website": "http://cyranch.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_012.html",
        "bells": "http://cyranch.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://cyranch.cfisd.net/en/news/school-news/",
        "studentnews": "https://cyranchnews.com/",
        "colorA": "cypressranch-colorA",
        "colorB": "cypressranch-colorB",
        "colorC": "cypressranch-colorC",
        "schooltype": "high"
    },
    {
        "name": "Cypress Ridge",
        "shortname": "cypressridge",
        "website": "http://cyridge.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_010.html",
        "bells": "http://cyridge.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://cyridge.cfisd.net/en/news/school-news/",
        "studentnews": "https://crhsrampage.com/",
        "colorA": "cypressridge-colorA",
        "colorB": "cypressridge-colorB",
        "colorC": "cypressridge-colorC",
        "schooltype": "high"
    },
    {
        "name": "Cypress Springs",
        "shortname": "cypresssprings",
        "website": "http://cysprings.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_009.html",
        "bells": "http://cysprings.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://cysprings.cfisd.net/en/news/school-news/",
        "studentnews": null,
        "colorA": "cypresssprings-colorA",
        "colorB": "cypresssprings-colorB",
        "colorC": "cypresssprings-colorC",
        "schooltype": "high"
    },
    {
        "name": "Cypress Woods",
        "shortname": "cypresswoods",
        "website": "http://cywoods.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_011.html",
        "bells": "http://cywoods.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://cywoods.cfisd.net/en/news/school-news/",
        "studentnews": "https://www.thecrimsonconnection.com/",
        "colorA": "cypresswoods-colorA",
        "colorB": "cypresswoods-colorB",
        "colorC": "cypresswoods-colorC",
        "schooltype": "high"
    },
    {
        "name": "Jersey Village",
        "shortname": "jerseyvillage",
        "website": "http://jerseyvillage.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_003.html",
        "bells": "http://jerseyvillage.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://jerseyvillage.cfisd.net/en/news/school-news/",
        "studentnews": "https://jvhsperegrine.com/",
        "colorA": "jerseyvillage-colorA",
        "colorB": "jerseyvillage-colorB",
        "colorC": "jerseyvillage-colorC",
        "schooltype": "high"
    },
    {
        "name": "Langham Creek",
        "shortname": "langhamcreek",
        "website": "http://langhamcreek.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_005.html",
        "bells": "http://langhamcreek.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://langhamcreek.cfisd.net/en/news/school-news/",
        "studentnews": "https://lchowler.net/",
        "colorA": "langhamcreek-colorA",
        "colorB": "langhamcreek-colorB",
        "colorC": "langhamcreek-colorC",
        "schooltype": "high"
    },
    {
        "name": "Windfern School of Choice",
        "shortname": "windfernschoolofchoice",
        "website": "http://windfern.cfisd.net",
        "faculty": "https://app.cfisd.net/urlcap/campus_list_008.html",
        "bells": "http://windfern.cfisd.net/en/parents-students/schedules/bell-schedule/",
        "basicnews": "http://windfern.cfisd.net/en/news/school-news/",
        "studentnews": null,
        "colorA": "windfernschoolofchoice-colorA",
        "colorB": "windfernschoolofchoice-colorB",
        "colorC": "windfernschoolofchoice-colorC",
        "schooltype": "high"
    }
];
